import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import ReactQueryProvider from "@/components/Providers/Provider";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Brand the test app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ReactQueryProvider>
    <html lang="en">
      <body
        className={inter.className}
      >
         <Nav/>

                    {children}

      </body>
    </html>
         </ReactQueryProvider>
  );
}
